# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-20 17:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MTRCharpyImpacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('direction', models.CharField(max_length=255)),
                ('temperature_unit', models.CharField(max_length=5)),
                ('temperature', models.SmallIntegerField()),
                ('impact_unit', models.CharField(max_length=255)),
                ('impact1', models.CharField(max_length=255)),
                ('impact2', models.CharField(max_length=255)),
                ('impact3', models.CharField(max_length=255)),
                ('LAT_EXP_unit', models.CharField(max_length=5)),
                ('LAT_EXP1', models.SmallIntegerField()),
                ('LAT_EXP2', models.SmallIntegerField()),
                ('LAT_EXP3', models.SmallIntegerField()),
                ('Shear_D_F1', models.SmallIntegerField()),
                ('Shear_D_F2', models.SmallIntegerField()),
                ('Shear_D_F3', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MTRChemistry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample', models.CharField(max_length=100)),
                ('c', models.FloatField()),
                ('mn', models.FloatField()),
                ('p', models.FloatField()),
                ('chemistry_notes', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MTRCustomers',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MTRGrainSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result1', models.DecimalField(decimal_places=3, max_digits=3)),
                ('result2', models.DecimalField(decimal_places=3, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='MTRHardnessSub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('range', models.BooleanField()),
                ('quadrant', models.CharField(max_length=255)),
                ('OD1', models.DecimalField(decimal_places=3, max_digits=3)),
                ('OD2', models.DecimalField(decimal_places=3, max_digits=3)),
                ('OD3', models.DecimalField(decimal_places=3, max_digits=3)),
                ('OD_Avg', models.DecimalField(decimal_places=3, max_digits=3)),
                ('MW_1', models.DecimalField(decimal_places=3, max_digits=3)),
                ('MW_2', models.DecimalField(decimal_places=3, max_digits=3)),
                ('MW_3', models.DecimalField(decimal_places=3, max_digits=3)),
                ('MW_Avg', models.DecimalField(decimal_places=3, max_digits=3)),
                ('ID1', models.DecimalField(decimal_places=3, max_digits=3)),
                ('ID2', models.DecimalField(decimal_places=3, max_digits=3)),
                ('ID3', models.DecimalField(decimal_places=3, max_digits=3)),
                ('ID_Avg', models.DecimalField(decimal_places=3, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='MTRHeatTreatment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mill_performed', models.BooleanField()),
                ('heat_treat_vendor', models.CharField(max_length=255)),
                ('lot_number', models.SmallIntegerField()),
                ('total_pieces', models.SmallIntegerField()),
                ('heat_treatment_notes', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MTRHeatTreatmentProcess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.CharField(max_length=2)),
                ('pieces', models.SmallIntegerField()),
                ('process', models.CharField(max_length=255)),
                ('time_units', models.CharField(max_length=5)),
                ('time', models.DateTimeField()),
                ('temperature_unit', models.CharField(max_length=5)),
                ('range', models.BooleanField()),
                ('temperature', models.SmallIntegerField()),
                ('cooling_method', models.CharField(max_length=255)),
                ('process_notes', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MTRMaterialTesting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_id', models.CharField(max_length=255)),
                ('batch', models.CharField(max_length=5)),
                ('sample', models.CharField(max_length=255)),
                ('vendor_performed', models.BooleanField()),
                ('lab_vendor', models.CharField(max_length=100)),
                ('mechanical_properties', models.BooleanField()),
                ('mech_prop_active_results', models.BooleanField()),
                ('prolongation_surface_hardness', models.BooleanField()),
                ('prolongation_surface_hardness_active_results', models.BooleanField()),
                ('quadrant_hardness', models.BooleanField()),
                ('quadrant_active_results', models.BooleanField()),
                ('charpy_impacts', models.BooleanField()),
                ('charpy_impacts_active_results', models.BooleanField()),
                ('grain_size', models.BooleanField()),
                ('ndt', models.BooleanField()),
                ('testing_notes', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='MTRMaterialType',
            fields=[
                ('material_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('material_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MTRMechanicalProperties',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tensile_yield_unit', models.CharField(max_length=5)),
                ('tensile', models.IntegerField()),
                ('yield_2_off', models.IntegerField()),
                ('yield_6_eul', models.IntegerField()),
                ('elong_in_2_percent', models.IntegerField()),
                ('reduction_in_area', models.FloatField()),
                ('yield_strength_ratio', models.FloatField()),
                ('mechanical_properties_notes', models.CharField(max_length=100)),
                ('test_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quickstart.MTRMaterialTesting')),
            ],
        ),
        migrations.CreateModel(
            name='MTRNonDestructiveTesting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('astm_a388', models.BooleanField()),
                ('test_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quickstart.MTRMaterialTesting')),
            ],
        ),
        migrations.CreateModel(
            name='MTRRelations',
            fields=[
                ('relation_id', models.AutoField(primary_key=True, serialize=False)),
                ('mtr', models.CharField(max_length=255)),
                ('heat_number', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MTRS',
            fields=[
                ('mtr', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('mill', models.CharField(max_length=100)),
                ('available_inventory', models.BooleanField()),
                ('mtr_attachment', models.CharField(max_length=100)),
                ('customer_specification', models.CharField(max_length=100)),
                ('mtr_notes', models.CharField(max_length=255)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quickstart.MTRCustomers')),
            ],
        ),
        migrations.CreateModel(
            name='MTRSpecifications',
            fields=[
                ('specification_id', models.AutoField(primary_key=True, serialize=False)),
                ('specification_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MTRSub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shape', models.CharField(max_length=10)),
                ('dimensions_unit', models.CharField(max_length=255)),
                ('outside_diameter', models.FloatField()),
                ('inside_diameter', models.FloatField()),
                ('wall_thickness', models.FloatField()),
                ('int_quality', models.CharField(max_length=255)),
                ('condition', models.CharField(max_length=255)),
                ('reduction_type', models.CharField(max_length=10)),
                ('reduction_ratio', models.CharField(max_length=50)),
                ('material_notes', models.CharField(max_length=255)),
                ('material_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quickstart.MTRMaterialType')),
                ('relation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quickstart.MTRRelations')),
            ],
        ),
        migrations.CreateModel(
            name='MTRSurfaceHardness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prolongation_surface', models.BooleanField()),
                ('quadrant', models.BooleanField()),
                ('location', models.CharField(max_length=255)),
                ('test_units', models.CharField(max_length=255)),
                ('test_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quickstart.MTRMaterialTesting')),
            ],
        ),
        migrations.AddField(
            model_name='mtrs',
            name='specifications',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quickstart.MTRSpecifications'),
        ),
        migrations.AddField(
            model_name='mtrmaterialtesting',
            name='relation_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quickstart.MTRRelations'),
        ),
        migrations.AddField(
            model_name='mtrheattreatmentprocess',
            name='relation_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quickstart.MTRRelations'),
        ),
        migrations.AddField(
            model_name='mtrheattreatment',
            name='relation_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quickstart.MTRRelations'),
        ),
        migrations.AddField(
            model_name='mtrhardnesssub',
            name='test_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quickstart.MTRMaterialTesting'),
        ),
        migrations.AddField(
            model_name='mtrgrainsize',
            name='test_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quickstart.MTRMaterialTesting'),
        ),
        migrations.AddField(
            model_name='mtrchemistry',
            name='relation_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quickstart.MTRRelations'),
        ),
        migrations.AddField(
            model_name='mtrcharpyimpacts',
            name='test_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quickstart.MTRMaterialTesting'),
        ),
    ]
